import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8faff',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
    background: 'linear-gradient(135deg, #e3f2fd 0%, #f3e5f5 100%)',
  },
  imagen: {
    width: 240,
    height: 120,
    marginBottom: 35,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#81c784',
    shadowColor: '#1976d2',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 15,
    elevation: 12,
    transform: [{ scale: 1 }],
  },
  textInput: {
    width: '100%',
    borderColor: '#42a5f5',
    borderWidth: 2,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 20,
    marginVertical: 12,
    backgroundColor: '#ffffff',
    fontSize: 17,
    color: '#0d47a1',
    shadowColor: '#1976d2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 6,
    fontFamily: 'System',
    letterSpacing: 0.5,
  },
  button: {
    backgroundColor: '#1565c0',
    paddingVertical: 18,
    paddingHorizontal: 48,
    borderRadius: 25,
    marginTop: 32,
    shadowColor: '#0d47a1',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 10,
    transform: [{ scale: 1 }],
    borderWidth: 1,
    borderColor: '#1976d2',
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  title: {
    fontSize: 34,
    fontWeight: '800',
    color: '#0d47a1',
    marginBottom: 32,
    textAlign: 'center',
    letterSpacing: 1.3,
    textShadowColor: 'rgba(13, 71, 161, 0.2)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    fontFamily: 'System',
  },
  headerText: {
    fontSize: 26,
    fontWeight: '700',
    color: '#1565c0',
    marginBottom: 16,
    textAlign: 'center',
    letterSpacing: 0.8,
    textShadowColor: 'rgba(21, 101, 192, 0.15)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  texto2: {
    color: '#42a5f5',
    textAlign: 'center',
    marginBottom: 24,
    marginHorizontal: 24,
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 24,
    letterSpacing: 0.3,
    opacity: 0.9,
  },
  buttonSecondary: {
    marginVertical: 16,
    backgroundColor: '#26c6da',
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 22,
    shadowColor: '#00acc1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#00bcd4',
  },
  // Estilos adicionales para mayor belleza
  gradientBackground: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  cardContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 24,
    padding: 32,
    marginHorizontal: 16,
    shadowColor: '#1976d2',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 15,
    borderWidth: 1,
    borderColor: 'rgba(66, 165, 245, 0.2)',
  },
  iconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#e3f2fd',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    shadowColor: '#1976d2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 8,
  },
  decorativeElement: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(66, 165, 245, 0.1)',
    top: -20,
    right: -20,
  },
  successText: {
    color: '#2e7d32',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 16,
    backgroundColor: 'rgba(76, 175, 80, 0.1)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(76, 175, 80, 0.3)',
  },
  errorText: {
    color: '#c62828',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 16,
    backgroundColor: 'rgba(244, 67, 54, 0.1)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(244, 67, 54, 0.3)',
  },
});