import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    padding: 24,
    backgroundColor: "#f0f4f8",
    alignItems: "center",
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    width: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 5,
    marginBottom: 20,
  },
  imagenPerfil: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginBottom: 16,
    borderWidth: 3,
    borderColor: "#4A90E2",
  },
  nombre: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#2c3e50",
    marginBottom: 4,
  },
  carrera: {
    fontSize: 16,
    color: "#34495e",
    marginBottom: 2,
  },
  info: {
    fontSize: 14,
    color: "#7f8c8d",
    marginBottom: 10,
  },
  descripcion: {
    fontSize: 15,
    color: "#4d4d4d",
    textAlign: "center",
  },
  section: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 18,
    width: "100%",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#2c3e50",
    marginBottom: 8,
    textAlign: "center",
  },
  sectionText: {
    fontSize: 15,
    color: "#4d4d4d",
    textAlign: "justify",
    lineHeight: 22,
  },
  boton: {
    backgroundColor: "#4A90E2",
    paddingVertical: 14,
    paddingHorizontal: 30,
    borderRadius: 12,
    marginTop: 10,
  },
  textoBoton: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
});
